version: '3.9'

services:

  backend:
    build: ./services/backend
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    ports:
      - 8000:8000
    volumes:
      - ./app/backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres_quiz:postgres_quiz@db/postgres_quiz
    depends_on:
      - db
  
  frontend:
    build:
      context: ./services/frontend
    ports:
      - 8080:80
    command: npm run serve
    volumes:
      - frontend:/app
  
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres_quiz
      - POSTGRES_PASSWORD=postgres_quiz
      - POSTGRES_DB=postgres_quiz
    expose:
      - 5432
    volumes:
      - quiz_data:/var/lib/postgresql/data/

volumes:
  quiz_data:
  frontend:
