"""1-migration

Revision ID: 2d51de6145c5
Revises: 18d4c8fba2f2
Create Date: 2022-12-10 12:24:47.153147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d51de6145c5'
down_revision = '18d4c8fba2f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
