"""4-migration

Revision ID: 7a86c76d0884
Revises: 61f4d34244d2
Create Date: 2022-12-12 11:03:03.172504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a86c76d0884'
down_revision = '61f4d34244d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
