"""2-migration

Revision ID: 9f173d7f5e91
Revises: 3267e9b16614
Create Date: 2022-12-14 19:58:20.267741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f173d7f5e91'
down_revision = '3267e9b16614'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'vote_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'vote_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('votes', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('votes', 'answer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'answer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('votes', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'vote_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('answers', 'vote_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
