"""3-migration

Revision ID: a40397ac08a3
Revises: 9f173d7f5e91
Create Date: 2022-12-16 11:34:48.139950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40397ac08a3'
down_revision = '9f173d7f5e91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
